/**
 * This code was generated by Builder.io.
 */
import React from "react";
import GuaranteedImprovement from "./GuaranteedImprovement";
import Header from "./Header";
import PathForBetterWork from "./PathForBetterWork";
import WhatIsAcc from "./WhatIsAcc";

const AccLayout: React.FC = () => {
  return (
    <main className="flex overflow-y-scroll h-screen flex-col bg-white snap-y snap-mandatory">
      <div className="snap-always snap-center">
        <Header />
      </div>
      <div className="snap-always snap-center">
        <WhatIsAcc />
      </div>
      <div className="snap-always snap-center">
        <PathForBetterWork />
      </div>
      {/* <div className="snap-always snap-center">
        <SafeAndSound />
      </div> */}
      <div className="snap-always snap-center">
        <GuaranteedImprovement />
      </div>
    </main>
  );
};

export default AccLayout;
