/**
 * This code was generated by Builder.io.
 */
import React from "react";
import "../../app/globals.css";
import Parallax from "./Parallax";
const Test: React.FC = () => {
  return (
    <>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Julius+Sans+One&display=swap');
    </style>
    <div className= "bg-sky-300">
      <Parallax />
    </div>

    
    </>
  );

};

export default Test;
